name: Build CBA page index

on:
  workflow_dispatch:
  push:
    paths:
      - 'public/mlb/MLB_CBA_2022.pdf'
      - 'scripts/build_cba_pages.mjs'
      - '.github/workflows/build-cba-pages.yml'

permissions:
  contents: write

jobs:
  build:
    # prevent infinite loops on our own commit
    if: ${{ !contains(github.event.head_commit.message, 'Auto-generate cba_pages.json') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pdfjs-dist (no save)
        run: npm i pdfjs-dist@4.2.67 --no-save

      - name: Build cba_pages.json
        run: node scripts/build_cba_pages.mjs

      - name: Show output
        run: |
          ls -lah public/mlb || true
          echo "Preview (first 500 chars):"
          head -c 500 public/mlb/cba_pages.json || true
          echo ""

      - name: Upload cba_pages.json artifact (for visibility)
        uses: actions/upload-artifact@v4
        with:
          name: cba_pages.json
          path: public/mlb/cba_pages.json
          if-no-files-found: error

      - name: Commit result
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -f public/mlb/cba_pages.json
          git commit -m "Auto-generate cba_pages.json" || echo "Nothing to commit"
          git push
